model:
  type: Equiformer
  checkpoint:
    path: ./trained_models/RDE2.pt
    type:  Equiformer
  encoder:
    input_feat_dim: 128
    node_feat_dim: 128
    num_nearest_neighbors: 8
    num_layers: 8
    dropout: 0.2
  use_plm: True

data:
  reset: False
  use_plm: True
  train_pdb_root: ./data/T50/train
  train_csv_path: ./data/T50/train.csv
  test_root: ./data/T50/test
  cache_dir: ./data/T50_cache
  transform:
  - type: select_atom
    resolution: backbone+CB
  - type: selected_interface_region_padding_patch
    fix_size: 128

train:
  loss_weights:
    regression: 1.0
  max_iters: 10_000
  val_freq: 50
  batch_size: 16
  seed: 2023
  max_grad_norm: 100.0
  optimizer:
    type: adam
    lr: 1.e-4  # (default: 3e-4)
    weight_decay: 0.0
    beta1: 0.9
    beta2: 0.999
  scheduler:
    type: plateau
    factor: 0.8
    patience: 5
    min_lr: 1.e-6
